name: check
on:
  push:
    paths:
      - "Trenev/**/*.jsfx"
      - "README.md"
      - ".reapack-index.conf"
      - ".github/workflows/check.yml"
      - ".github/workflows/deploy.yml"
  pull_request:
    paths:
      - "Trenev/**/*.jsfx"
      - "README.md"
      - ".reapack-index.conf"
      - ".github/workflows/check.yml"
      - ".github/workflows/deploy.yml"

jobs:
  reapack-index:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v4
    - name: Install Pandoc
      run: sudo apt-get install -yy pandoc
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - name: Install reapack-index
      run: gem install reapack-index
    - name: Validate packages
      run: reapack-index --check
